#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 1,
    label = "H2O + CO <=> HCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Average of [From training reaction 7 used for CO;CsO_H]
    Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Average of [From training reaction 7 used for CO;CsO_H]
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 2,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 0 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [Root_N-5CbCdCsHN->Cs_4CbCdCsHN->H_N-5CbCdHN->Cd]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 0 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [Root_N-5CbCdCsHN->Cs_4CbCdCsHN->H_N-5CbCdHN->Cd]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 3,
    label = "CO + CH3OH <=> HCOOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.127,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;CsO_H]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;CsO_H]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 4,
    label = "X + H2O <=> H2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [H2O;VacantSite]
    Euclidian distance = 3.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [H2O;VacantSite]
Euclidian distance = 3.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 5,
    label = "X + CO2 <=> CO2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
Euclidian distance = 1.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 6,
    label = "H* + CO2 <=> HCOO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 7,
    label = "HCOO* <=> COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'s^-1'), n=0, Ea=(50,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
family: Surface_Migration
""",
)

entry(
    index = 8,
    label = "H* + CO2 <=> COOH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 9,
    label = "X + HCOOH <=> HCOOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 10,
    label = "X + CH2O <=> CH2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
Euclidian distance = 1.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 11,
    label = "H* + CH2O <=> CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 12,
    label = "OH* + CH2O <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 13,
    label = "H* + HCOOH <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 14,
    label = "X + CH3OH <=> CH3OH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 15,
    label = "X + X + H2 <=> H* + H*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(3.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [H2;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [H2;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 16,
    label = "X + X + CO2 <=> O* + CO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 17,
    label = "X + X + H2O <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(146.749,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O-H;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [O-H;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 18,
    label = "X + X + CH2O <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(56.0932,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 19,
    label = "X + X + HCOOH <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(28.9194,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 20,
    label = "X + X + HCOOH <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(45.1097,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 21,
    label = "X + X + HCOOH <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(70.3735,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 22,
    label = "X + X + CH3OH <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(116.792,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 23,
    label = "X + X + HCOOCH3 <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(5.22202,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 24,
    label = "X + OH* <=> O* + H*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(69.5801,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [O-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 25,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(137.247,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [H2O;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [H2O;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 26,
    label = "X + CO2* <=> O* + CO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(66.7546,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;VacantSite] for rate rule [CO2;VacantSite]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from 30.6 to 66.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;VacantSite] for rate rule [CO2;VacantSite]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
Ea raised from 30.6 to 66.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 27,
    label = "X + HCO* <=> H* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(65.1434,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 28,
    label = "H* + CO2* <=> X + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(11.7643,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 29,
    label = "X + HCOO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(273.857,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C=O;VacantSite]
    Euclidian distance = 3.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C=O;VacantSite]
Euclidian distance = 3.0
family: Surface_Dissociation
""",
)

entry(
    index = 30,
    label = "H* + CO2* <=> X + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(30.0715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 31,
    label = "X + COOH* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(155.682,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 32,
    label = "X + HCOOH* <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(167.492,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 33,
    label = "X + HCOOH* <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(156.48,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 34,
    label = "X + HCOOH* <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(76.6991,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 35,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(62.2366,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [CH2R;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [CH2R;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 36,
    label = "H* + CH2O* <=> X + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(18.1704,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
    Euclidian distance = 2.23606797749979
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
Euclidian distance = 2.23606797749979
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 37,
    label = "OH* + CH2O* <=> X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
    Euclidian distance = 2.8284271247461903
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
Euclidian distance = 2.8284271247461903
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 38,
    label = "H* + HCOOH* <=> X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(63.4194,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
    Euclidian distance = 2.23606797749979
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
Euclidian distance = 2.23606797749979
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 39,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(233.528,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 40,
    label = "O* + CH2O* <=> H* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -64.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -64.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 41,
    label = "H2O* + CO* <=> H* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(16.1199,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 6.2 to 16.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 6.2 to 16.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 42,
    label = "OH* + CH2O* <=> H* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -101.35 kJ/mol
    Ea raised from -54.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -101.35 kJ/mol
Ea raised from -54.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 43,
    label = "H2O* + HCO* <=> H* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*C=R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -3.25 kJ/mol
    Ea raised from -4.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*C=R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -3.25 kJ/mol
Ea raised from -4.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 44,
    label = "O* + CH3OH* <=> H* + CH3O2*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(28.8914,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 16.1 to 28.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 16.1 to 28.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 45,
    label = "H2O* + CH2O* <=> H* + CH3O2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(31.4796,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 31.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 31.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 46,
    label = "O* + H2O* <=> OH* + OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(90.4374,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 46.1 to 90.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 46.1 to 90.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 47,
    label = "O* + HCO* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(125.999,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O;*C-H] for rate rule [O;*-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -0.85 kJ/mol"""),
    longDesc = 
"""
Estimated using template [O;*C-H] for rate rule [O;*-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -0.85 kJ/mol
""",
)

entry(
    index = 48,
    label = "O* + HCOO* <=> OH* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(159.962,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O;R-C-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O;R-C-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 49,
    label = "O* + COOH* <=> OH* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(12.8029,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O;R-O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O;R-O-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 50,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -9.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -9.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 51,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from -9.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from -9.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 52,
    label = "O* + HCOOH* <=> OH* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(15.8172,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 8.4 to 15.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 8.4 to 15.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 53,
    label = "O* + CH2O* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -4.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -4.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 54,
    label = "O* + CH3O* <=> OH* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(147.918,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 55,
    label = "O* + CH3O2* <=> OH* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(83.1346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O;R-C-H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O;R-C-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 56,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 57,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 58,
    label = "H2O* + CO* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(95.9661,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 47.9 to 96.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 47.9 to 96.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 59,
    label = "OH* + HCOO* <=> H2O* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(65.5552,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [OH;R-C-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [OH;R-C-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 60,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -9.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -9.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 61,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from -9.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from -9.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 62,
    label = "OH* + COOH* <=> H2O* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [OH;R-O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [OH;R-O-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 63,
    label = "OH* + HCOOH* <=> H2O* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -101.43 kJ/mol
    Ea raised from -56.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -101.43 kJ/mol
Ea raised from -56.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 64,
    label = "OH* + HCOOH* <=> H2O* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -78.75 kJ/mol
    Ea raised from -37.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -78.75 kJ/mol
Ea raised from -37.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 65,
    label = "OH* + CH2O* <=> H2O* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -98.11 kJ/mol
    Ea raised from -50.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -98.11 kJ/mol
Ea raised from -50.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 66,
    label = "OH* + CH3O* <=> H2O* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(56.843,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [OH;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [OH;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 67,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 68,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 69,
    label = "OH* + CH3O2* <=> H2O* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(9.9783,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [OH;R-C-H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [OH;R-C-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 70,
    label = "OH* + CH3OH* <=> H2O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -22.48 kJ/mol
    Ea raised from -10.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -22.48 kJ/mol
Ea raised from -10.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 71,
    label = "CO* + HCOO* <=> CO2* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(163.262,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 72,
    label = "CO* + COOH* <=> CO2* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(128.845,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 73,
    label = "CO* + HCOOH* <=> HCO* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -8.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -8.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 74,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(21.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 75,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(21.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 76,
    label = "CO* + CH2O* <=> HCO* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -2.5 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -2.5 to 0.0 kJ/mol.
""",
)

entry(
    index = 77,
    label = "CO* + CH3O* <=> HCO* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(151.219,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 78,
    label = "CO* + CH3O2* <=> COOH* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(110.286,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 79,
    label = "CO* + CH3O2* <=> HCO* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(86.4353,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 80,
    label = "CO* + CH3OH* <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(75.1026,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 37.7 to 75.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 37.7 to 75.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 81,
    label = "HCOO* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(141.721,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 82,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(116.823,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 83,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(116.823,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 84,
    label = "COOH* + COOH* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(91.9253,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 85,
    label = "HCO* + HCOO* <=> CO2* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(134.076,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 86,
    label = "HCO* + COOH* <=> CO2* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(109.179,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 87,
    label = "HCOO* + CH3O* <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(79.3485,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 88,
    label = "COOH* + CH3O* <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(54.4508,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 89,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(21.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 90,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(21.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 10.2 to 21.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 91,
    label = "HCO* + HCOOH* <=> HCOO* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -3.32 kJ/mol
    Ea raised from -5.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -3.32 kJ/mol
Ea raised from -5.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 92,
    label = "COOH* + CH2O* <=> HCO* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -19.36 kJ/mol
    Ea raised from -12.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -19.36 kJ/mol
Ea raised from -12.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 93,
    label = "HCO* + CH3O* <=> CH2O* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(125.364,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 94,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(78.4995,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 95,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(78.4995,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 96,
    label = "CH2O* + CH3O* <=> HCO* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -75.63 kJ/mol
    Ea raised from -40.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -75.63 kJ/mol
Ea raised from -40.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 97,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(116.823,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 98,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(116.823,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 99,
    label = "COOH* + HCOOH* <=> HCOO* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -22.68 kJ/mol
    Ea raised from -18.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -22.68 kJ/mol
Ea raised from -18.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 100,
    label = "HCOO* + CH3O* <=> CH2O* + HCOOH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(133.008,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 101,
    label = "HCOO* + CH3O2* <=> HCOOH* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(86.1437,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 102,
    label = "HCOOH* + CH3O* <=> HCOO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -78.95 kJ/mol
    Ea raised from -45.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -78.95 kJ/mol
Ea raised from -45.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 103,
    label = "COOH* + CH3O* <=> CH2O* + HCOOH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(108.111,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 104,
    label = "COOH* + CH3O2* <=> HCOOH* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(61.246,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 105,
    label = "HCOOH* + CH3O* <=> COOH* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -56.27 kJ/mol
    Ea raised from -27.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -56.27 kJ/mol
Ea raised from -27.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 106,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(78.4995,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 107,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(78.4995,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 108,
    label = "CH3O* + CH3O2* <=> HCOOH* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(23.7715,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 109,
    label = "CH3O* + CH3O* <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(70.6362,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 110,
    label = "CH3O* <=> OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'s^-1'), n=0, Ea=(50,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Migration
""",
)

entry(
    index = 111,
    label = "X + X + CH3OH <=> H* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.099, n=0, Ea=(73.3869,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [CH3OH;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [CH3OH;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 112,
    label = "X + CH3O2* <=> O* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(158.436,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 113,
    label = "X + CH3OH* <=> H* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(4.17e+17,'m^2/(mol*s)'), n=0, Ea=(75.4815,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [CH3R;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [CH3R;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 114,
    label = "H* + CH2O <=> OC[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 115,
    label = "H* + CH2O* <=> X + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;H*]
    Euclidian distance = 3.1622776601683795
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;H*]
Euclidian distance = 3.1622776601683795
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 116,
    label = "O* + CH3OH* <=> OH* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(12.6203,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 7.4 to 12.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 7.4 to 12.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 117,
    label = "O* + OC[Pt] <=> OH* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(77.0521,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O;R-O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O;R-O-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 118,
    label = "OH* + CH3OH* <=> H2O* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -80.00 kJ/mol
    Ea raised from -38.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -80.00 kJ/mol
Ea raised from -38.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 119,
    label = "OH* + OC[Pt] <=> H2O* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(1.59618,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [OH;R-O-H]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [OH;R-O-H]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 120,
    label = "CO* + CH3OH* <=> HCO* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(18.1491,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 9.1 to 18.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 9.1 to 18.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 121,
    label = "HCOO* + OC[Pt] <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(118.275,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 122,
    label = "COOH* + OC[Pt] <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(93.3778,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 123,
    label = "CO* + OC[Pt] <=> HCO* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(205.03,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_vdW
""",
)

entry(
    index = 124,
    label = "CH2O* + OC[Pt] <=> HCO* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -18.11 kJ/mol
    Ea raised from -11.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -18.11 kJ/mol
Ea raised from -11.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 125,
    label = "HCOOH* + OC[Pt] <=> HCOO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -21.43 kJ/mol
    Ea raised from -17.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -21.43 kJ/mol
Ea raised from -17.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 126,
    label = "COOH* + CH3OH* <=> HCOOH* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -1.25 kJ/mol
    Ea raised from -1.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -1.25 kJ/mol
Ea raised from -1.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 127,
    label = "HCOO* + OC[Pt] <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(171.935,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 128,
    label = "COOH* + OC[Pt] <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(147.038,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 129,
    label = "OC[Pt] + CH3O2* <=> HCOOH* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.36e+17,'m^2/(mol*s)'), n=0, Ea=(62.6986,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 130,
    label = "HCO* + OC[Pt] <=> CH2O* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(164.291,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 131,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 132,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 133,
    label = "OC[Pt] + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(148.49,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 134,
    label = "CH3O* + CH3OH* <=> OC[Pt] + CH3OH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -57.52 kJ/mol
    Ea raised from -28.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -57.52 kJ/mol
Ea raised from -28.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 135,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O-H]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 136,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.179e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-CH3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-CH3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 137,
    label = "X + X + CH3OH <=> OH* + C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(31.2514,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 30.8 to 31.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 30.8 to 31.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 138,
    label = "X + X + HCOOCH3 <=> HCOO* + C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(3.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 139,
    label = "X + CH3O* <=> O* + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(188.202,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 140,
    label = "X + CH3OH* <=> OH* + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(161.549,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 141,
    label = "H* + CH3OH* <=> H2O* + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -11.18 kJ/mol
    Ea raised from -1.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -11.18 kJ/mol
Ea raised from -1.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 142,
    label = "CO* + CH3OH* <=> COOH* + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(11.3244,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 5.1 to 11.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 5.1 to 11.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 143,
    label = "HCO* + CH3OH* <=> HCOOH* + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;*C=R]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -14.42 kJ/mol
    Ea raised from -5.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;*C=R]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -14.42 kJ/mol
Ea raised from -5.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 144,
    label = "C[Pt] + CH3O2* <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.18e+17,'m^2/(mol*s)'), n=0, Ea=(85.467,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 145,
    label = "CO2 + C <=> HCOOCH3",
    degeneracy = 8.0,
    kinetics = Arrhenius(A=(3.19262e-07,'m^3/(mol*s)'), n=3.39053, Ea=(356.925,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_5CbCdCsHN->Cs_N-4CbCdCsHN->Cs',), comment="""Estimated from node Root_5CbCdCsHN->Cs_N-4CbCdCsHN->Cs
    Multiplied by reaction path degeneracy 8.0"""),
    longDesc = 
"""
Estimated from node Root_5CbCdCsHN->Cs_N-4CbCdCsHN->Cs
Multiplied by reaction path degeneracy 8.0
""",
)

entry(
    index = 146,
    label = "X + X + C <=> H* + C[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=3.02, n=0, Ea=(71.199,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [CH4;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 68.0 to 71.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [CH4;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 68.0 to 71.2 kJ/mol to match endothermicity of reaction.
""",
)

