#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + H2 <=> H* + H*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.046, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 1,
    label = "X + OH* <=> O* + H*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.39e+15,'m^2/(mol*s)'), n=0, Ea=(77300,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 2,
    label = "X + H2O <=> H2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 3,
    label = "X + H2O* <=> H* + OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.15e+15,'m^2/(mol*s)'), n=0, Ea=(101400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 4,
    label = "O* + H2O* <=> OH* + OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(90500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 5,
    label = "CO* <=> X + CO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+11,'1/s'), n=0, Ea=(169500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 6,
    label = "X + CO2 <=> CO2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 7,
    label = "O* + CO* <=> X + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+21,'cm^2/(mol*s)'), n=0, Ea=(117600,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 8,
    label = "OH* + CO* <=> H* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(38700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 9,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 10,
    label = "H2O + CO <=> HCOOH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.254,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO;RO_H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;RO_H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 11,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 12,
    label = "CO + CH3OH <=> HCOOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.127,'cm^3/(mol*s)'), n=3.7, Ea=(223.258,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;CsO_H]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 7 CH4O + CO <=> C2H4O2 in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;CsO_H]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 13,
    label = "CO2 + CH4 <=> HCOOCH3",
    degeneracy = 8.0,
    kinetics = Arrhenius(A=(36240,'cm^3/(mol*s)'), n=2.83, Ea=(331.373,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template [CO2;C_methane] for rate rule [CO2_Od;C_methane]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 8.0
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Estimated using template [CO2;C_methane] for rate rule [CO2_Od;C_methane]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 8.0
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 14,
    label = "H* + CO2 <=> HCOO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 15,
    label = "HCOO* <=> COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'s^-1'), n=0, Ea=(50,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
family: Surface_Migration
""",
)

entry(
    index = 16,
    label = "H* + CO2 <=> COOH*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 17,
    label = "X + HCOOH <=> HCOOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 18,
    label = "X + CH2O <=> CH2O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O;VacantSite]
Euclidian distance = 1.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 19,
    label = "H* + CH2O <=> CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 20,
    label = "OH* + CH2O <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 21,
    label = "H* + HCOOH <=> CH3O2*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 22,
    label = "X + CH3OH <=> CH3OH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 23,
    label = "X + X + CO2 <=> O* + CO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 24,
    label = "X + X + CH2O <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 25,
    label = "X + X + HCOOH <=> OH* + HCO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 26,
    label = "X + X + HCOOH <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 27,
    label = "X + X + HCOOH <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 28,
    label = "X + X + CH3OH <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 29,
    label = "X + X + HCOOCH3 <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 30,
    label = "X + HCO* <=> H* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(65.1434,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 31,
    label = "H* + CO2* <=> X + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(23.737,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 32,
    label = "X + HCOO* <=> O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(218.932,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 33,
    label = "H* + CO2* <=> X + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(30.9913,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 34,
    label = "X + COOH* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(130.608,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 35,
    label = "X + HCOOH* <=> OH* + HCO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(136.693,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 36,
    label = "X + HCOOH* <=> H* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(105.03,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 37,
    label = "X + HCOOH* <=> OH* + HCO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(136.693,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 38,
    label = "X + HCOOH* <=> H* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(71.5549,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 39,
    label = "X + CH2O* <=> H* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(62.2613,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 40,
    label = "H* + CH2O* <=> X + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(18.1704,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
    Euclidian distance = 2.23606797749979
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
Euclidian distance = 2.23606797749979
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 41,
    label = "OH* + CH2O* <=> X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
    Euclidian distance = 2.8284271247461903
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;HO*]
Euclidian distance = 2.8284271247461903
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 42,
    label = "H* + HCOOH* <=> X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(26.2575,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
    Euclidian distance = 2.23606797749979
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;H*]
Euclidian distance = 2.23606797749979
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 43,
    label = "X + CH3OH* <=> H* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(150.934,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 44,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Od;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Od;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 45,
    label = "H2 + CO2 <=> HCOOH",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.51e+09,'cm^3/(mol*s)'), n=1.23, Ea=(309.198,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
    This reaction matched rate rule [CO2_Cdd;H2]
    family: 1,3_Insertion_CO2"""),
    longDesc = 
"""
Matched reaction 1 H2 + CO2 <=> CH2O2 in 1,3_Insertion_CO2/training
This reaction matched rate rule [CO2_Cdd;H2]
family: 1,3_Insertion_CO2
""",
)

entry(
    index = 46,
    label = "O* + CH2O* <=> H* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -31.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -31.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 47,
    label = "H2O* + CO* <=> H* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(59.3405,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 27.8 to 59.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 27.8 to 59.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 48,
    label = "OH* + CH2O* <=> H* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -28.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -28.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 49,
    label = "H* + HCOOH* <=> H2O* + HCO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -22.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -22.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 50,
    label = "O* + CH3OH* <=> H* + CH3O2*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(28.8914,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 16.1 to 28.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 16.1 to 28.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 51,
    label = "H2O* + CH2O* <=> H* + CH3O2*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(31.4796,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 31.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 31.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 52,
    label = "O* + HCO* <=> OH* + CO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(125.999,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O;*C-H] for rate rule [O;*-C-H]
    Euclidian distance = 1.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [O;*C-H] for rate rule [O;*-C-H]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 53,
    label = "OH* + CO2* <=> O* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(36.8811,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 54,
    label = "OH* + CO2* <=> O* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(42.9746,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 55,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -3.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -3.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 56,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from -3.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from -3.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 57,
    label = "O* + HCOOH* <=> OH* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(9.06759,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 3.7 to 9.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 3.7 to 9.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 58,
    label = "O* + CH2O* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -4.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -4.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 59,
    label = "OH* + CH2O* <=> O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(32.2051,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 60,
    label = "OH* + HCOOH* <=> O* + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(38.9983,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 61,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 62,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 63,
    label = "H2O* + CO* <=> OH* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(95.9661,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 47.9 to 96.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 47.9 to 96.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 64,
    label = "X + HCOOH* <=> OH* + HCO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(136.693,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 65,
    label = "X + HCOOH* <=> OH* + HCO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(136.693,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 66,
    label = "OH* + HCOO* <=> H2O* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(49.2723,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;OH]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;OH]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 67,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -3.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C=R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -3.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 68,
    label = "O* + HCOOH* <=> OH* + HCOO*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from -3.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from -3.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 69,
    label = "OH* + COOH* <=> H2O* + CO2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O-H;OH]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O-H;OH]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 70,
    label = "OH* + HCOOH* <=> H2O* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -49.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -49.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 71,
    label = "OH* + HCOOH* <=> H2O* + COOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Ea raised from -42.5 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Ea raised from -42.5 to 0.0 kJ/mol.
""",
)

entry(
    index = 72,
    label = "OH* + CH2O* <=> H2O* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -50.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -50.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 73,
    label = "OH* + CH3O* <=> H2O* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(56.843,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;OH]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;OH]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 74,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-C-3R;*=O]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 75,
    label = "O* + CH3OH* <=> OH* + CH3O*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(69.5738,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_vdW
    Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_vdW
Ea raised from 36.0 to 69.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 76,
    label = "OH* + CH3O2* <=> H2O* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(45.8445,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;OH]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;OH]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 77,
    label = "OH* + CH3OH* <=> H2O* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -10.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -10.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 78,
    label = "CO2* + HCO* <=> CO* + HCOO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(35.4063,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 79,
    label = "CO2* + HCO* <=> CO* + COOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(41.4999,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
    Euclidian distance = 4.47213595499958
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
Euclidian distance = 4.47213595499958
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 80,
    label = "CO* + HCOOH* <=> HCO* + HCOO*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from -1.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from -1.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 81,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(14.5964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 82,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(14.5964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 83,
    label = "CO* + CH2O* <=> HCO* + HCO*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -2.5 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -2.5 to 0.0 kJ/mol.
""",
)

entry(
    index = 84,
    label = "HCO* + CH2O* <=> CO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(30.7304,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 85,
    label = "COOH* + CH2O* <=> CO* + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(30.8626,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
    Euclidian distance = 2.23606797749979
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-R]
Euclidian distance = 2.23606797749979
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 86,
    label = "HCO* + HCOOH* <=> CO* + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(37.5235,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C;*C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 87,
    label = "CO* + CH3OH* <=> HCO* + CH3O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(75.1026,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 37.7 to 75.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 37.7 to 75.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 88,
    label = "HCOO* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(116.875,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 89,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(107.009,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 90,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(107.009,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 91,
    label = "COOH* + COOH* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(97.1435,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 92,
    label = "HCO* + HCOO* <=> CO2* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(117.794,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 93,
    label = "HCO* + COOH* <=> CO2* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(107.928,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 94,
    label = "HCOO* + CH3O* <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(63.0656,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 95,
    label = "COOH* + CH3O* <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(53.1998,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 96,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(14.5964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 97,
    label = "CO* + HCOOH* <=> HCO* + COOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(14.5964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Abstraction_vdW
    Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
family: Surface_Abstraction_vdW
Ea raised from 5.4 to 14.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 98,
    label = "HCO* + HCOOH* <=> HCOO* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(3.94816,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from 0.7 to 3.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from 0.7 to 3.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 99,
    label = "HCO* + HCOOH* <=> COOH* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(19.2408,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Ea raised from 7.9 to 19.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C=R]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Ea raised from 7.9 to 19.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 100,
    label = "HCO* + CH3O* <=> CH2O* + CH2O*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(125.364,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 101,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(114.366,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;Adsorbate1]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;Adsorbate1]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 102,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(114.366,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 103,
    label = "CH2O* + CH3O* <=> HCO* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -40.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -40.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 104,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(107.009,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 105,
    label = "COOH* + HCOO* <=> CO2* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(107.009,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 106,
    label = "COOH* + HCOOH* <=> HCOO* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -7.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C=R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -7.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 107,
    label = "HCOO* + CH3O* <=> CH2O* + HCOOH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(124.446,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 108,
    label = "HCOO* + CH3O2* <=> HCOOH* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(113.447,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 109,
    label = "HCOOH* + CH3O* <=> HCOO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Ea raised from -39.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Ea raised from -39.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 110,
    label = "COOH* + CH3O* <=> CH2O* + HCOOH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(114.58,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 111,
    label = "COOH* + CH3O2* <=> HCOOH* + HCOOH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(103.581,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 112,
    label = "HCOOH* + CH3O* <=> COOH* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    family: Surface_Abstraction_Single_vdW
    Ea raised from -32.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
family: Surface_Abstraction_Single_vdW
Ea raised from -32.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 113,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(114.366,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 114,
    label = "HCO* + CH3O2* <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(114.366,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;Adsorbate1]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;Adsorbate1]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 115,
    label = "CH3O* + CH3O2* <=> HCOOH* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(59.6378,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 116,
    label = "CH3O* + CH3O* <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(70.6362,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 117,
    label = "CH3O* <=> OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3e+13,'s^-1'), n=0, Ea=(50,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Migration"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Migration
""",
)

entry(
    index = 118,
    label = "X + X + CH3OH <=> H* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.03, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 119,
    label = "X + CH3O2* <=> O* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(158.394,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 120,
    label = "X + CH3OH* <=> H* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(75.878,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 121,
    label = "H* + CH2O <=> OC[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=5e-06, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 122,
    label = "H* + CH2O* <=> X + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;H*]
    Euclidian distance = 3.1622776601683795
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;H*]
Euclidian distance = 3.1622776601683795
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 123,
    label = "O* + CH3OH* <=> OH* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(12.6203,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 7.4 to 12.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 7.4 to 12.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 124,
    label = "OH* + CH2O* <=> O* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(8.16195,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
Euclidian distance = 3.1622776601683795
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 125,
    label = "OH* + CH3OH* <=> H2O* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -38.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -38.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 126,
    label = "OH* + OC[Pt] <=> H2O* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(1.59618,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [O-H;OH]
    Euclidian distance = 0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [O-H;OH]
Euclidian distance = 0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 127,
    label = "CO* + CH3OH* <=> HCO* + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(18.1491,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW
    Ea raised from 9.1 to 18.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
Ea raised from 9.1 to 18.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 128,
    label = "HCOO* + OC[Pt] <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(101.993,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 129,
    label = "COOH* + OC[Pt] <=> CO2* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(92.1268,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 130,
    label = "HCO* + CH2O* <=> CO* + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(6.68719,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*C-H]
    Euclidian distance = 3.605551275463989
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*C-H]
Euclidian distance = 3.605551275463989
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 131,
    label = "CH2O* + OC[Pt] <=> HCO* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -11.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -11.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 132,
    label = "HCOOH* + OC[Pt] <=> HCOO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -10.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -10.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 133,
    label = "HCOOH* + OC[Pt] <=> COOH* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction_Single_vdW
    Ea raised from -3.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction_Single_vdW
Ea raised from -3.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 134,
    label = "HCOO* + OC[Pt] <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(163.373,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 135,
    label = "COOH* + OC[Pt] <=> CH2O* + HCOOH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(153.507,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 136,
    label = "OC[Pt] + CH3O2* <=> HCOOH* + CH3OH*",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.4e+17,'m^2/(mol*s)'), n=0, Ea=(98.5648,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 137,
    label = "HCO* + OC[Pt] <=> CH2O* + CH2O*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(164.291,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 138,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 139,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 140,
    label = "OC[Pt] + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(148.49,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 141,
    label = "CH3O* + CH3OH* <=> OC[Pt] + CH3OH*",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -28.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -28.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 142,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(9.6e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [C-H;Adsorbate1]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 143,
    label = "CH3O* + OC[Pt] <=> CH2O* + CH3OH*",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(109.563,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
    Euclidian distance = 1.0
    family: Surface_Abstraction_Beta_double_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;Adsorbate1] for rate rule [O-H;Adsorbate1]
Euclidian distance = 1.0
family: Surface_Abstraction_Beta_double_vdW
""",
)

entry(
    index = 144,
    label = "X + O* + CH4 <=> OH* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+18,'cm^5/(mol^2*s)'), n=0.7, Ea=(42000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 145,
    label = "X + OH* + CH4 <=> H2O* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(10000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 146,
    label = "H* + CH3X <=> X + X + CH4",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.3e+21,'cm^2/(mol*s)'), n=0, Ea=(50000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 147,
    label = "X + X + CH3OH <=> OH* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 148,
    label = "X + X + HCOOCH3 <=> HCOO* + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 149,
    label = "X + CH3O* <=> O* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(188.16,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 150,
    label = "X + CH3OH* <=> OH* + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(161.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 151,
    label = "X + CH3OH* <=> OH* + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(161.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 152,
    label = "H* + CH3OH* <=> H2O* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -1.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -1.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 153,
    label = "CO* + CH3OH* <=> COOH* + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(54.5449,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
    Euclidian distance = 4.242640687119285
    family: Surface_Abstraction_vdW
    Ea raised from 26.7 to 54.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*=C=R]
Euclidian distance = 4.242640687119285
family: Surface_Abstraction_vdW
Ea raised from 26.7 to 54.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 154,
    label = "HCOOH* + CH3X <=> HCO* + CH3OH*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;*C-3R]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction_Single_vdW
    Ea raised from -21.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;*C-3R]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction_Single_vdW
Ea raised from -21.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 155,
    label = "CH2O* + CH3OH* <=> CH3X + CH3O2*",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(26.684,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-OH]
    Euclidian distance = 3.605551275463989
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 26.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-OH]
Euclidian distance = 3.605551275463989
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 26.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 156,
    label = "X + CH3OH* <=> OH* + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(161.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 157,
    label = "X + CH3OH* <=> OH* + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(3.2e+17,'m^2/(mol*s)'), n=0, Ea=(161.346,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_vdW
""",
)

